### ISSUE TITLE
Removing init() function

### ISSUE THREAD

**Issue by codegoalie** [leonelquinteros/hubspot#1]
Hello! Thanks for creating this library. I'm just starting to use it for a project and I'm wondering if you're open to me creating a few PRs to clean up some stuff and add a bit of functionality around [Events](https://legacydocs.hubspot.com/docs/methods/enterprise_events/http_api).

If so, I'd love to start with a small change to remove the `init()` function. We should be able to keep the same API by simply moving the environment variable fetching into the `NewClientConfig` call.

Thanks again!

**Comment by leonelquinteros** [comment]
Hey! Thank you for your interest and for contributing. 

I guess it makes sense to move that there, I don't remember now why it was that way, probably didn't think about that too much at the moment. 

As long as the API is untouched and backwards compatibility is ensured, I welcome all contributions. 

I'll look forward for your first PR and following discussions about new features. 

Thanks again for your contribution!
